tarname: HeFESTo_Mars_Profiles_NPS_NoJCCValid   #(Suffix: '_Train', '_Test', '_Valid') - Base name for training, test, and validation datasets. Only _Train and _Test are loaded. 
    
warm_start: HeFESTo_Mars_Profiles_NPS_NoJCCValid_train5 #pGeoDynamicsIsentropicNoCrApr20_train1 #None #pGeoDynamicsIsothemalNoCrMar11_train6 #None #pGeoDynPTNoCrBinaries #None # 102CrMoleLinear

tune7: # No dropout for models with bulk loss (breaks it for some reason), so let's investigate other regularization options
  strategy: upper # Train encoder and saturation predictor, all else frozen. Upper portion of model not used at all for efficiency
  low_regularization: 0.0batchnormdropout0.5
  high_regularization: 0.0batchnormdropout0.5
  sweep: true
  batch_size: 1024 
  epochs: 7
  learning_rate: 5E-4
  early_stopping_patience: 4
  max_N: 5E5
  tune_params:
    #lowWD: [0, 1e-6, 1e-5, 1e-4, 1e-3]
    highWD: [0, 1e-4, 1e-3, 1e-2]
    noise: [0, 0.005, 0.01, 0.02, 0.05]

  loss_config:
    binary:
      weight: 0
    chemistry:
      type: symmetric_rel_l2
      weight: 100
    moles:
      type: huber
      weight: 100
    bulk:
      type: symmetric_rel_l2
      weight: 100
  which_heads_to_freeze: ['encoder', 'sat_head']
  
tune8: # No dropout for models with bulk loss (breaks it for some reason), so let's investigate other regularization options
  strategy: finetune # Train encoder and saturation predictor, all else frozen. Upper portion of model not used at all for efficiency
  sweep: true
  batch_size: 1024 
  epochs: 7
  learning_rate: 5E-4
  early_stopping_patience: 4
  max_N: 5E5
  tune_params:
    lowWD: [0, 1e-6, 1e-5, 1e-4, 1e-3]
    highWD: [0, 1e-4, 1e-3, 1e-2]
    noise: [0, 0.005, 0.01, 0.02, 0.05]

  loss_config:
    binary:
      weight: 1
    chemistry:
      type: symmetric_rel_l2
      weight: 100
    moles:
      type: huber
      weight: 100
    bulk:
      type: symmetric_rel_l2
      weight: 100

  tune9: # No dropout for models with bulk loss (breaks it for some reason), so let's investigate other regularization options
  strategy: finetune # Train encoder and saturation predictor, all else frozen. Upper portion of model not used at all for efficiency
  sweep: true
  batch_size: 1024 
  epochs: 15
  learning_rate: 5E-4
  early_stopping_patience: 4
  max_N: 5E5
  tune_params:
    lowWD: [0, 1e-6, 1e-5, 1e-4, 1e-3]
    highWD: [0, 1e-4, 1e-3, 1e-2]
    noise: [0, 0.005, 0.01, 0.02, 0.05]

  loss_config:
    binary:
      weight: 1
    chemistry:
      type: symmetric_rel_l2
      weight: 100
    moles:
      type: huber
      weight: 100
    bulk:
      type: symmetric_rel_l2
      weight: 100
  