tarname: 'HeFESTo_041026_NPT_low_noise_adiabats'       #(Suffix: '_Train', '_Test', '_Valid') - Base name for training, test, and validation datasets. Only _Train and _Test are loaded. 
    
warm_start: None #pGeoDynamicsIsentropicNoCrApr20_train1 #None #pGeoDynamicsIsothemalNoCrMar11_train6 #None #pGeoDynPTNoCrBinaries #None # 102CrMoleLinear


  
encoderLayerUp: 1
encoderLayerDown: 0
middleLayerUp: 2
middleLayerDown: 0
low_regularization: 0.2batchnormdropout0.5
high_regularization: 0.15batchnormdropout0.5
activation_leak: 0.05
lowWD: 1E-3
highWD: 1E-4
noise: 0.01 # 2%
description: ""


tune1: # find best encoder geometry 
  #best_loss: 7.45870
  strategy: lower # Train encoder and saturation predictor, all else frozen. Upper portion of model not used at all for efficiency
  batch_size: 1024 
  epochs: 5
  #learning_rate: 1E-3
  scheduler:
  type: OneCycleLR #CosineAnnealingLR # Any scheduler in optim.lr_scheduler, e.g. 'CosineAnnealingLR', 'ReduceLROnPlateau', 'CosineAnnealingWarmRestarts'.
  args:
    #T_max: 10 # Then args to pass to the scheduler, e.g. factor, patience, T_0, etc. See PyTorch documentation for details.
    max_lr: 1E-3
    epochs: 6
    steps_per_epoch: 1960
  early_stopping_patience: 2
  #max_N: 5E5
  tune_params: # These go in the specified order
    encoderLayer: [[1,0], [1,1], [2,2], [3,2], [2,0], [2,1]]
  binweights:
    akimotoite: 10
    hp-clinopyroxene: 4
    plagioclase: 10
    spinel: 4
    stishovite: 5


tune2: # initialize encoder and sat heads 
  strategy: lower # Train encoder and saturation predictor, all else frozen. Upper portion of model not used at all for efficiency
  sweep: true
  batch_size: 1024 
  epochs: 5
  scheduler:
  type: OneCycleLR #CosineAnnealingLR # Any scheduler in optim.lr_scheduler, e.g. 'CosineAnnealingLR', 'ReduceLROnPlateau', 'CosineAnnealingWarmRestarts'.
  args:
    #T_max: 10 # Then args to pass to the scheduler, e.g. factor, patience, T_0, etc. See PyTorch documentation for details.
    max_lr: 1E-3
    epochs: 6
    steps_per_epoch: 1960
  early_stopping_patience: 2
  #max_N: 5E5
  inherit_loss: True # Whether to inherit loss config from previous training stage when tuning
  tune_params: # These go in the specified order
    lowWD: [0, 1e-4, 1e-3, 1e-2]
    noise: [0, 0.1, 0.05, 0.01]
    low_regularization: [0.3batchnormdropout0.5, 0.2batchnormdropout0.5, 0.1batchnormdropout0.5, 0.0batchnormdropout0.5]
  binweights:
    akimotoite: 10
    hp-clinopyroxene: 4
    plagioclase: 10
    spinel: 4
    stishovite: 5

tune3: #Find best middle brain geometry
  #best_loss: 8.6477
  strategy: upper #
  batch_size: 1024 
  epochs: 5
  #learning_rate: 1E-3
  early_stopping_patience: 2

  type: OneCycleLR #CosineAnnealingLR # Any scheduler in optim.lr_scheduler, e.g. 'CosineAnnealingLR', 'ReduceLROnPlateau', 'CosineAnnealingWarmRestarts'.
  args:
    #T_max: 10 # Then args to pass to the scheduler, e.g. factor, patience, T_0, etc. See PyTorch documentation for details.
    max_lr: 1E-3
    epochs: 6
    steps_per_epoch: 1960

  tune_params: 
    middleLayer: [[1,0], [1,1], [2,2], [3,2], [2,0], [2,1]]
  
  loss_config:
      binary:
        weight: 0
      chemistry:
        type: symmetric_rel_l2
        weight: 100
      moles:
        type: huber
        weight: 0
      bulk:
        type: symmetric_rel_l2
        weight: 0
  which_heads_to_freeze: ['encoder', 'sat_head', 'mole_head']
  binweights:
    melts-liquid: 5
    spinel: 5


tune4: # initialize middle brain and chemistry heads with best geometry from tune3
  #best_loss: 8.6477
  inherit_loss: True # Whether to inherit loss config from previous training stage when tuning
  sweep: true
  strategy: upper #
  batch_size: 1024 
  epochs: 5
  #learning_rate: 1E-3
  early_stopping_patience: 2

  type: OneCycleLR #CosineAnnealingLR # Any scheduler in optim.lr_scheduler, e.g. 'CosineAnnealingLR', 'ReduceLROnPlateau', 'CosineAnnealingWarmRestarts'.
  args:
    #T_max: 10 # Then args to pass to the scheduler, e.g. factor, patience, T_0, etc. See PyTorch documentation for details.
    max_lr: 1E-3
    epochs: 6
    steps_per_epoch: 1960

  tune_params: # These go in the specified order
      highWD: [0, 1e-4, 1e-3, 1e-2]
      noise: [0, 0.1, 0.05, 0.01]
      high_regularization: [0.10batchnormdropout0.5, 0.2batchnormdropout0.5, 0.05batchnormdropout0.5]

  
  loss_config:
      binary:
        weight: 0
      chemistry:
        type: symmetric_rel_l2
        weight: 100
      moles:
        type: huber
        weight: 0
      bulk:
        type: symmetric_rel_l2
        weight: 0
  which_heads_to_freeze: ['encoder', 'sat_head', 'mole_head']
  binweights:
    akimotoite: 10
    hp-clinopyroxene: 4
    plagioclase: 10
    spinel: 4
    stishovite: 5
  

tune5: # Initialize mole heads
  strategy: upper # Train encoder and saturation predictor, all else frozen. Upper portion of model not used at all for efficiency
  sweep: true
  batch_size: 1024 
  epochs: 5
  early_stopping_patience: 2
  scheduler:
    type: OneCycleLR #CosineAnnealingLR # Any scheduler in optim.lr_scheduler, e.g. 'CosineAnnealingLR', 'ReduceLROnPlateau', 'CosineAnnealingWarmRestarts'.
    args:
      #T_max: 10 # Then args to pass to the scheduler, e.g. factor, patience, T_0, etc. See PyTorch documentation for details.
      max_lr: 1E-3
      epochs: 6
      steps_per_epoch: 1960
  tune_params: # These go in the specified order
    highWD: [0, 1e-4, 1e-3, 1e-2]
    noise: [0, 0.1, 0.05, 0.01]
    high_regularization: [0.10batchnormdropout0.5, 0.2batchnormdropout0.5, 0.05batchnormdropout0.5]

  #DictFilePath: pGeoDynPTCrMole
  loss_config:
    binary:
      weight: 0
    chemistry:
      type: symmetric_rel_l2
      weight: 0
    moles:
      type: huber
      weight: 50
    bulk:
      type: symmetric_rel_l2
      weight: 0
  which_heads_to_freeze: ['encoder', 'sat_head', 'middleBrain']
  binweights:
    akimotoite: 10
    hp-clinopyroxene: 4
    plagioclase: 10
    spinel: 4
    stishovite: 5

train1: # Increase number for another layer of training
  strategy: upper # Train encoder and saturation predictor, all else frozen. Upper portion of model not used at all for efficiency
  batch_size: 1024 
  epochs: 70
  learning_rate: 5E-4
  early_stopping_patience: 20
  scheduler:
    type: CosineAnnealingLR # Any scheduler in optim.lr_scheduler, e.g. 'CosineAnnealingLR', 'ReduceLROnPlateau', 'CosineAnnealingWarmRestarts'.
    args:
      T_max: 10 # Then args to pass to the scheduler, e.g. factor, patience, T_0, etc. See PyTorch documentation for details.
  #DictFilePath: pGeoDynPTCrNoBulk
  loss_config:
    binary:
      weight: 1
    chemistry:
      type: symmetric_rel_l2
      weight: 100
    moles:
      type: huber
      weight: 50
    bulk:
      type: symmetric_rel_l2
      weight: 0
  which_heads_to_freeze: ['encoder'] # ['encoder', 'sat_head', 'middleBrain', 'chem_heads'] #['encoder', 'sat_head', 'middleBrain', 'chem_heads']
  binweights:
    akimotoite: 10
    hp-clinopyroxene: 4
    plagioclase: 10
    spinel: 4
    stishovite: 5

tune6: # No dropout for models with bulk loss (breaks it for some reason), so let's investigate other regularization options
  strategy: upper # Train encoder and saturation predictor, all else frozen. Upper portion of model not used at all for efficiency
  batch_size: 1024 
  epochs: 7
  learning_rate: 5E-4
  early_stopping_patience: 4
  max_N: 5E5
  tune_params:
    lowWD: [0, 1e-6, 1e-5, 1e-4, 1e-3]
    highWD: [0, 1e-4, 1e-3, 1e-2]
    noise: [0, 0.005, 0.01, 0.02, 0.05]

  loss_config:
    binary:
      weight: 0
    chemistry:
      type: symmetric_rel_l2
      weight: 100
    moles:
      type: huber
      weight: 50
    bulk:
      type: symmetric_rel_l2
      weight: 1000
  which_heads_to_freeze: ['encoder', 'sat_head']


train5: # Increase number for another layer of training
  strategy: finetune # Train encoder and saturation predictor, all else frozen. Upper portion of model not used at all for efficiency
  batch_size: 1024 
  epochs: 70
  learning_rate: 5E-4
  early_stopping_patience: 20
  scheduler:
    type: CosineAnnealingLR # Any scheduler in optim.lr_scheduler, e.g. 'CosineAnnealingLR', 'ReduceLROnPlateau', 'CosineAnnealingWarmRestarts'.
    args:
      T_max: 10 # Then args to pass to the scheduler, e.g. factor, patience, T_0, etc. See PyTorch documentation for details.
  max_N: null # none, 0 and inf all mean 'no limit'
  #DictFilePath: pGeoDynPTCrBulk
  loss_config:
    binary:
      weight: 0
    chemistry:
      type: symmetric_rel_l2
      weight: 100
    moles:
      type: huber
      weight: 50
    bulk:
      type: symmetric_rel_l2
      weight: 1000
  which_heads_to_freeze: ['encoder', 'sat_head'] #['encoder', 'sat_head', 'middleBrain', 'chem_heads']
  binweights:
    akimotoite: 10
    hp-clinopyroxene: 4
    plagioclase: 10
    spinel: 4
    stishovite: 5

train6: # Increase number for another layer of training
  strategy: finetune # Train encoder and saturation predictor, all else frozen. Upper portion of model not used at all for efficiency
  batch_size: 1024 
  lowWD: 0 # No WD for frozen layers
  epochs: 70
  learning_rate: 5E-4
  early_stopping_patience: 20
  scheduler:
    type: CosineAnnealingLR # Any scheduler in optim.lr_scheduler, e.g. 'CosineAnnealingLR', 'ReduceLROnPlateau', 'CosineAnnealingWarmRestarts'.
    args:
      T_max: 10 # Then args to pass to the scheduler, e.g. factor, patience, T_0, etc. See PyTorch documentation for details.
  max_N: null # none, 0 and inf all mean 'no limit'
  #DictFilePath: pGeoDynPTCrFull
  loss_config:
    binary:
      weight: 1
    chemistry:
      type: symmetric_rel_l2
      weight: 100
    moles:
      type: huber
      weight: 50
    bulk:
      type: symmetric_rel_l2
      weight: 1000
  which_heads_to_freeze: [] # ['encoder', 'sat_head'] #['encoder', 'sat_head', 'middleBrain', 'chem_heads']
  binweights:
    akimotoite: 10
    hp-clinopyroxene: 4
    plagioclase: 10
    spinel: 4
    stishovite: 5

tune7:
  #best_loss: 7.45870
  strategy: lower # Train encoder and saturation predictor, all else frozen. Upper portion of model not used at all for efficiency
  sweep: true
  batch_size: 1024 
  epochs: 15
  learning_rate: 5E-4
  early_stopping_patience: 2
  max_N: 5E5
  tune_params: # These go in the specified order
    lowWD: [0, 1e-4, 1e-3, 1e-2]
    noise: [0, 0.1, 0.05, 0.01]

train7: # Increase number for another layer of training
  strategy: lower # Train encoder and saturation predictor, all else frozen. Upper portion of model not used at all for efficiency
  batch_size: 1024 
  epochs: 70
  learning_rate: 5E-4
  early_stopping_patience: 25
  scheduler:
    type: CosineAnnealingLR # Any scheduler in optim.lr_scheduler, e.g. 'CosineAnnealingLR', 'ReduceLROnPlateau', 'CosineAnnealingWarmRestarts'.
    args:
      T_max: 10 # Then args to pass to the scheduler, e.g. factor, patience, T_0, etc. See PyTorch documentation for details.
  binweights:
    akimotoite: 10
    hp-clinopyroxene: 4
    plagioclase: 10
    spinel: 4
    stishovite: 5


tune8: # No dropout for models with bulk loss (breaks it for some reason), so let's investigate other regularization options
  strategy: upper # Train encoder and saturation predictor, all else frozen. Upper portion of model not used at all for efficiency
  batch_size: 1024 
  epochs: 7
  learning_rate: 5E-4
  early_stopping_patience: 4
  max_N: 5E5
  tune_params:
    lowWD: [0, 1e-6, 1e-5, 1e-4, 1e-3]
    highWD: [0, 1e-4, 1e-3, 1e-2]
    noise: [0, 0.005, 0.01, 0.02, 0.05]

  loss_config:
    binary:
      weight: 0
    chemistry:
      type: symmetric_rel_l2
      weight: 100
    moles:
      type: huber
      weight: 50
    bulk:
      type: symmetric_rel_l2
      weight: 1000
  which_heads_to_freeze: ['encoder', 'sat_head']

  
train8: # Increase number for another layer of training
  strategy: finetune # Train encoder and saturation predictor, all else frozen. Upper portion of model not used at all for efficiency
  batch_size: 1024 
  lowWD: 0 # No WD for frozen layers
  epochs: 50
  learning_rate: 5E-4
  early_stopping_patience: 25
  scheduler:
    type: CosineAnnealingLR # Any scheduler in optim.lr_scheduler, e.g. 'CosineAnnealingLR', 'ReduceLROnPlateau', 'CosineAnnealingWarmRestarts'.
    args:
      T_max: 10 # Then args to pass to the scheduler, e.g. factor, patience, T_0, etc. See PyTorch documentation for details.
  max_N: null # none, 0 and inf all mean 'no limit'
  #DictFilePath: pGeoDynPTCrFull
  loss_config:
    binary:
      weight: 1
    chemistry:
      type: symmetric_rel_l2
      weight: 100
    moles:
      type: huber
      weight: 50
    bulk:
      type: symmetric_rel_l2
      weight: 1000
  which_heads_to_freeze: [] # ['encoder', 'sat_head'] #['encoder', 'sat_head', 'middleBrain', 'chem_heads']
  binweights:
    akimotoite: 10
    hp-clinopyroxene: 4
    plagioclase: 10
    spinel: 4
    stishovite: 5