tarname: '102General' #(Suffix: '_Train', '_Test', '_Valid') - Base name for training, test, and validation datasets. Only _Train and _Test are loaded. 

warm_start: None

tune: # Comment this out to skip training, warm start from a saved model must be provided
  lower_model:
    epochs: 20
    learning_rate: 1e-3
    early_stopping_patience: 2
    encoderLayer: [[1, 1], [1, 0], [2, 2], [2, 1], [3, 2]] # [upsampling layers, downsampling layers]Numbers of upsamplings to try (factors of 2 in neuron increase for each layer)
    low_regularization: [dropout0, batchnormdropout0, layernormdropout0]
    activation_leak: 0.05

  upper_model:
    epochs: 20
    learning_rate: 1e-3
    early_stopping_patience: 2
    middleLayer: [[1, 1], [1, 0], [2, 2], [2, 1], [3, 2]] # Numbers of upsamplings to try (factors of 2 in neuron increase for each layer)
    high_regularization: [dropout0, batchnormdropout0, layernormdropout0]
    highWD: [0, 1e-6, 1e-5, 1e-4]
    noise: [0, 0.01, 0.05]

train1: # Increase number for another layer of training
  strategy: lower # Train encoder and saturation predictor, all else frozen. Upper portion of model not used at all for efficiency
  batch_size: 1024 
  epochs: 20
  learning_rate: 1e-3
  early_stopping_patience: 3
  scheduler:
    type: ReduceLROnPlateau # Any scheduler in optim.lr_scheduler, e.g. 'CosineAnnealingLR', 'ReduceLROnPlateau', 'CosineAnnealingWarmRestarts'.
    args:
      factor: 0.2 # Then args to pass to the scheduler, e.g. factor, patience, T_0, etc. See PyTorch documentation for details.
      patience: 3
      min_lr: 1e-5

    


train2: 
  strategy: upper # Train upper portion of model, encoder frozen. Saturation predictor still trained, but not used for loss calculation.
  batch_size: 1024 
  epochs: 20
  learning_rate: 1e-3
  early_stopping_patience: 3
  scheduler:
    type: ReduceLROnPlateau # Any scheduler in optim.lr_scheduler, e.g. 'CosineAnnealingLR', 'ReduceLROnPlateau', 'CosineAnnealingWarmRestarts'.
    args:
      factor: 0.2 # Then args to pass to the scheduler, e.g. factor, patience, T_0, etc. See PyTorch documentation for details.
      patience: 3
      min_lr: 1e-5

    weight_dict: # Loss multipliers for each phase, used to upweight underperforming phases. Can be set to 1 for all phases to use unweighted loss.
    'olivine': 3
    'nepheline': 15
    'leucite': 10
    'alloy-solid': 5
    'muscovite': 3
    'k-feldspar': 5

train3: 
  strategy: finetune # Train entire model with free flowing gradients
  batch_size: 1024 
  epochs: 20
  learning_rate: 1e-3
  early_stopping_patience: 3
  scheduler:
    type: ReduceLROnPlateau # Any scheduler in optim.lr_scheduler, e.g. 'CosineAnnealingLR', 'ReduceLROnPlateau', 'CosineAnnealingWarmRestarts'.
    args:
      factor: 0.2 # Then args to pass to the scheduler, e.g. factor, patience, T_0, etc. See PyTorch documentation for details.
      patience: 3
      min_lr: 1e-5