tarname: '102General' #(Suffix: '_Train', '_Test', '_Valid') - Base name for training, test, and validation datasets. Only _Train and _Test are loaded. 

warm_start: None

model:
  encoderLayerUp: 2
  encoderLayerDown: 1
  middleLayerUp: 2
  middleLayerDown: 1
  low_regularization: dropout0
  high_regularization: batchnormdropout0
  activation_leak: 0.05
  lowWD: 1E-5
  highWD: 1E-5
  noise: 0.02 # 2%
  description: ""

train1: # Increase number for another layer of training
  strategy: lower # Train encoder and saturation predictor, all else frozen. Upper portion of model not used at all for efficiency
  batch_size: 1024 
  epochs: 1
  learning_rate: 1e-3
  early_stopping_patience: 3
  scheduler:
    type: ReduceLROnPlateau # Any scheduler in optim.lr_scheduler, e.g. 'CosineAnnealingLR', 'ReduceLROnPlateau', 'CosineAnnealingWarmRestarts'.
    args:
      factor: 0.2 # Then args to pass to the scheduler, e.g. factor, patience, T_0, etc. See PyTorch documentation for details.
      patience: 3
      min_lr: 1e-6
  max_N: null
  DictFilePath: 110GeneralBinaries

train2: 
  strategy: upper # Train upper portion of model, encoder frozen. Saturation predictor still trained, but not used for loss calculation.
  batch_size: 1024 
  epochs: 25
  learning_rate: 1e-3
  early_stopping_patience: 3
  scheduler:
    type: ReduceLROnPlateau # Any scheduler in optim.lr_scheduler, e.g. 'CosineAnnealingLR', 'ReduceLROnPlateau', 'CosineAnnealingWarmRestarts'.
    args:
      factor: 0.2 # Then args to pass to the scheduler, e.g. factor, patience, T_0, etc. See PyTorch documentation for details.
      patience: 3
      min_lr: 1e-6
  DictFilePath: 110GeneralHeads
  loss_config:
    bulk:
      type: symmetric_rel_l2
      weight: 0.0
  

train3: 
  strategy: finetune # Train entire model with free flowing gradients
  batch_size: 1024 
  epochs: 25
  learning_rate: 1e-3
  early_stopping_patience: 3
  scheduler:
    type: ReduceLROnPlateau # Any scheduler in optim.lr_scheduler, e.g. 'CosineAnnealingLR', 'ReduceLROnPlateau', 'CosineAnnealingWarmRestarts'.
    args:
      factor: 0.2 # Then args to pass to the scheduler, e.g. factor, patience, T_0, etc. See PyTorch documentation for details.
      patience: 3
      min_lr: 1e-5
  DictFilePath: 110GeneralWhole
  loss_config:
    bulk:
      type: symmetric_rel_l2
      weight: 1

