"""Shared output location for figures/animations generated by ``scripts/``.

Every plotting script writes into ``<repo>/plots/`` (optionally a named
sub-folder).  That directory is git-ignored and is not part of the package /
wheel, so running the research scripts never dirties the tree or leaks build
artifacts into a release.

Usage:
    from _plot_output import PLOTS_DIR, plot_path, plots_dir

    fig.savefig(plot_path("my_figure.png"))              # -> <repo>/plots/my_figure.png
    out = plots_dir("melts_comparison")                  # -> <repo>/plots/melts_comparison/ (created)
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PLOTS_DIR = REPO_ROOT / "plots"


def plots_dir(subdir: str | None = None) -> Path:
    """Return ``<repo>/plots`` (or a sub-folder of it), creating it if needed."""
    d = PLOTS_DIR if subdir is None else PLOTS_DIR / subdir
    d.mkdir(parents=True, exist_ok=True)
    return d


def plot_path(name: str, subdir: str | None = None) -> Path:
    """Return the path a figure named ``name`` should be written to under ``plots/``.

    The containing directory is created; only a bare filename should be passed
    as ``name`` (use ``subdir`` for nesting).
    """
    return plots_dir(subdir) / name


def resolve_out(user_path, default_name: str, subdir: str | None = None) -> Path:
    """Resolve an optional user-supplied output path.

    ``user_path`` given  -> honoured as-is (its parent is created).
    ``user_path`` None   -> ``plots/<subdir>/<default_name>``.
    """
    if user_path is not None:
        p = Path(user_path)
        p.parent.mkdir(parents=True, exist_ok=True)
        return p
    return plot_path(default_name, subdir)
